check-updates: false
debug: false

# Аирдроп использует таймер по умолчанию,
# Его можно выключить в конфиге аирдропа.
timers:
  timer-1:
    name: timer-1
    tick-speed: 20 # Один тик аирдропа каждые 20 тиков сервера (раз в секунду)
    type: ticker # тип тикающий
    tick-type: all # all | by_chance - вызывает тик у всех аирдропов, by_chance - выбирает случайный и вызывает тик только у него
    linked-airdrops:
      custom_airdrop_id: '100' # <airdrop id>: 'extra' extra - это дополнительная информация. При типе by_chance в extra указывается шанс того что этот аирдроп будет тикать. при all можно ничего не указывать

  timer-2:
    name: timer-2
    time-zone: 'Europe/Moscow'
    tick-speed: 20 # Один тик аирдропа каждые 20 тиков сервера (раз в секунду)
    type: waiter
    linked-airdrops:
      custom_airdrop_id:
        - '10:00'
        - '15:30'
        - '14:30'
        - '14:40'

summoners:
  item-1:
    id: default
    modelData: 0 # 0 для отключения
    material: SOUL_CAMPFIRE
    name: '&aПризыватель аирдропа'
    lore:
      - '&r '
      - '&r&f Этот предмет призывает аирдроп'
      - '&r&f Чтобы им воспользоваться кликни по блоку'
      - '&r&f на который ты хочешь призвать аирдроп'
      - '&r '
    clone: true # призывать клон аирдропа вместо его самого
    usePlayerLoc: true # призывать аирдроп на место призыва
    checkUpBlocks: true # проверять блоки над аирдропом
    regionCheck: true # проверять регион
    minY: 30 # минимальная высота для призыва
    maxY: 120 # максимальная высота для призыва
    black-list-worlds: # в каких мирах запрещено призывать аирдроп
      - spawn
    airDrops: # аирдропы которые может призвать этот "маяк"
      - 'example:100'