# Проверять обновления плагина?
check-updates: false
# Режим отладки (вывод дополнительной информации в консоль)
debug: false

# Настройки таймеров - управляют запуском аирдропов по времени
timers:
  # Таймер №1 - Тикающий таймер
  timer-1:
    name: timer-1
    tick-speed: 20 # Скорость тиков (в тиках сервера, 20 тиков = 1 секунда)
    type: ticker # Тип таймера: ticker - постоянно тикающий
    tick-type: all # Режим работы: all - тикают все аирдропы, by_chance - выбирается случайный
    linked-airdrops:
      custom_airdrop_id: '100' # ID аирдропа: значение (при all - можно оставить пустым, при by_chance - шанс в %)

  # Таймер №2 - Таймер ожидания (запуск по расписанию)
  timer-2:
    name: timer-2
    time-zone: 'Europe/Moscow' # Часовой пояс для корректного расчета времени
    tick-speed: 20 # Частота проверки времени (в тиках сервера)
    type: waiter # Тип таймера: waiter - запуск по расписанию
    linked-airdrops:
      custom_airdrop_id:
        - '10:00' # 10:00 утра
        - '15:30' # 15:30 дня
        - '14:30' # 14:30 дня
        - '14:40' # 14:40 дня

  # Таймер №3 - Случайный таймер ожидания
  timer-3:
    name: timer-3
    time-zone: 'Europe/Moscow'
    tick-speed: 20
    type: random_waiter
    appearance-times: # Время, когда происходит случайный выбор аирдропа
      - '12:00' # 12:00 дня - запуск случайного аирдропа
      - '16:00' # 16:00 дня - запуск случайного аирдропа
      - '20:00' # 20:00 вечера - запуск случайного аирдропа
    weighted-airdrops: # Список аирдропов с шансами выпадения (ID: вес)
      custom_airdrop_id: 100 # Вес 100 (100% шанс, так как только один аирдроп)

# Настройки призывателей аирдропов (предметы для ручного вызова)
summoners:
  item-1:
    id: default # Уникальный ID призывателя
    modelData: 0 # Custom Model Data для текстуры предмета (0 - отключить)
    material: SOUL_CAMPFIRE # Материал предмета
    name: '&aПризыватель аирдропа' # Отображаемое имя предмета
    lore: # Описание предмета
      - '&r '
      - '&r&f Этот предмет призывает аирдроп'
      - '&r&f Чтобы им воспользоваться кликни по блоку'
      - '&r&f на который ты хочешь призвать аирдроп'
      - '&r '
    clone: true # Создавать клон аирдропа вместо использования оригинала
    usePlayerLoc: true # Использовать местоположение игрока для призыва
    checkUpBlocks: true # Проверять блоки над местом призыва
    regionCheck: true # Проверять разрешенные регионы для призыва
    minY: 30 # Минимальная высота для призыва (Y координата)
    maxY: 120 # Максимальная высота для призыва (Y координата)
    black-list-worlds: # Список миров, где запрещено призывать аирдропы
      - spawn
    airDrops: # Список аирдропов, которые можно призвать этим предметом
      - 'example:100' # Аирдроп "example" с шансом 100%